name: Go

on:
  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25.9', '1.26.2']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: set env
        run: go env -w GOTOOLCHAIN=go${{ matrix.go-version }}+auto

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -cover ./...
